// Generated by IcedCoffeeScript 1.8.0-c
(function() {
  var Promise, clusters, couch_utils, instances, _;

  _ = require('underscore');

  Promise = require('promise');

  instances = require('./instances');

  couch_utils = require('../couch_utils');

  clusters = {};

  clusters.get_cluster = function(client, cluster_id, callback) {
    return client.get(cluster_id, callback);
  };

  clusters.handle_get_cluster = function(req, resp) {
    var client, cluster_id;
    cluster_id = req.params.cluster_id;
    client = req.couch;
    return clusters.get_cluster(client, cluster_id).pipe(resp);
  };

  clusters.create_cluster = function(client, opts) {
    console.log(opts.instances);
    return Promise.all(opts.instances.map(instances.create_instance)).then(function(created_instances) {
      var cluster, ensure_db, moirai_db;
      cluster = {
        instances: created_instances
      };
      moirai_db = client.use('moirai');
      ensure_db = Promise.denodeify(couch_utils.ensure_db);
      return ensure_db(moirai_db, 'insert', cluster).then(function(couch_resp) {
        return Promise.resolve(_.extend(cluster, {
          _id: couch_resp.id,
          _rev: couch_resp.rev
        }));
      })["catch"](function(err) {
        return Promise.reject(new Error(err));
      });
    })["catch"](function() {
      return Promise.reject(new Error('Failed to create at least one instance'));
    });
  };

  clusters.handle_create_cluster = function(req, resp) {
    var cluster_opts, create_cluster;
    cluster_opts = req.body || {};
    create_cluster = Promise.denodeify(clusters.create_cluster);
    return create_cluster(req.couch, cluster_opts).then(function(cluster_doc) {
      return resp.status(201).send(JSON.stringify(cluster_doc));
    })["catch"](function(err) {
      return resp.status(500).send(JSON.stringify({
        error: 'internal error',
        msg: err
      }));
    });
  };

  clusters.handle_get_clusters = function(req, resp) {
    return resp.send('NOT IMPLEMENTED');
  };

  clusters.handle_get_cluster = function(req, resp) {
    return resp.send('NOT IMPLEMENTED');
  };

  clusters.handle_update_cluster = function(req, resp) {
    return resp.send('NOT IMPLEMENTED');
  };

  clusters.handle_destroy_cluster = function(req, resp) {
    return resp.send('NOT IMPLEMENTED');
  };

  clusters.handle_add_instance = function(req, resp) {
    return resp.send('NOT IMPLEMENTED');
  };

  module.exports = clusters;

}).call(this);
