// Generated by CoffeeScript 1.9.1
(function() {
  var _, a, do_action, validate_doc_update;

  do_action = require('./shared/do_action');

  validate_doc_update = require('./shared/validate_doc_update').validate_doc_update;

  _ = require('./underscore');

  a = {};

  a.get_doc_type = function(doc) {
    if (doc._id.indexOf('_') < 0) {
      return void 0;
    }
    return doc._id.split('_')[0];
  };

  a.do_actions = {
    cluster: {
      'c-': function(doc, action, actor) {
        return doc.instances.forEach(function(instance) {
          return instance.state = 'terminate';
        });
      }
    },
    create: {
      'c+': function(doc, action, actor) {
        return _.extend(doc, {
          _id: 'cluster_' + doc._id,
          name: action.record.name,
          created: +new Date(),
          instances: action.record.instances.map(function(instance) {
            return {
              id: instance.id,
              name: instance.tags.Name,
              size: instance.InstanceType
            };
          })
        });
      }
    }
  };

  a.validate_actions = {
    cluster: {
      'c+': function(event, actor, old_doc, new_doc) {},
      'c-': function(event, actor, old_doc, new_doc) {}
    }
  };

  a.do_action = do_action(a.do_actions, a.get_doc_type);

  a.validate_doc_update = validate_doc_update(a.validate_actions, a.get_doc_type);

  a.mixin = function(dd) {
    dd.validate_doc_update = a.validate_doc_update;
    return dd.updates.do_action = a.do_action;
  };

  module.exports = a;

}).call(this);
