// Generated by CoffeeScript 1.9.3
(function() {
  var _, actions, audit, dd, emit;

  _ = require('underscore');

  actions = require('./actions');

  audit = require('pantheon-helpers').design_docs.audit;

  dd = {
    views: {
      active_clusters: {
        map: function(doc) {
          var get_doc_type, i, instance, len, ref;
          get_doc_type = function(doc) {
            if (doc._id.indexOf('_') < 0) {
              return void 0;
            }
            return doc._id.split('_')[0];
          };
          if (get_doc_type(doc) === 'cluster' && doc.instances.length) {
            ref = doc.instances;
            for (i = 0, len = ref.length; i < len; i++) {
              instance = ref[i];
              if (instance.state !== 'terminate') {
                emit(doc._id);
                return;
              }
            }
          }
        }
      }
    },
    lists: {
      get_docs: function(header, req) {
        var out, row, val;
        out = [];
        while ((row = getRow())) {
          val = row.doc;
          out.push(val);
        }
        return JSON.stringify(out);
      },
      get_docs_without_audit: function(header, req) {
        var out, row, val;
        out = [];
        while ((row = getRow())) {
          val = row.doc;
          delete val.audit;
          out.push(val);
        }
        return JSON.stringify(out);
      }
    },
    shows: {},
    updates: {},
    rewrites: []
  };

  audit.mixin(dd);

  actions.mixin(dd);

  try {
    require('underscore');
    dd.emitted = [];
    emit = function(k, v) {
      return dd.emitted.push({
        k: k,
        v: v
      });
    };
  } catch (_error) {}

  module.exports = dd;

}).call(this);
