// Generated by CoffeeScript 1.9.1
(function() {
  var app, bodyParser, conf, couch_utils, express, pantheonMiddleware, ref, routes, server;

  pantheonMiddleware = require('pantheon-helpers/lib/middleware');

  conf = require('./config');

  couch_utils = require('./couch_utils');

  express = require('express');

  bodyParser = require('body-parser');

  routes = require('./routes');

  couch_utils.nano_system_user.db.create('moirai');

  app = express();

  app.use(bodyParser.json());

  app.use(pantheonMiddleware.auth(conf));

  app.use(pantheonMiddleware.couch(couch_utils));

  routes(app);

  server = app.listen(((ref = conf.APP) != null ? ref.PORT : void 0) || 5000, function() {
    var host, port;
    host = server.address().address;
    port = server.address().port;
    return console.log('app listening at http://%s:%s', host, port);
  });

}).call(this);
