// Generated by CoffeeScript 1.9.3
(function() {
  var config, config_secret, deepExtend, e;

  deepExtend = require('pantheon-helpers').utils.deepExtend;

  try {
    config_secret = require('./config_secret');
  } catch (_error) {
    e = _error;
    config_secret = {};
  }

  config = {
    COUCHDB: {
      HOST: 'localhost',
      PORT: 5984,
      HTTPS: false,
      SYSTEM_USER: 'admin'
    },
    APP: {
      PORT: 5001
    },
    PRIVATE_KEY_FILE: __dirname + '/../moirai.key',
    SSH_USER: 'ec2-user',
    COUCH_PWD: '',
    AUTHORIZED_KEY_DEFAULTS: [],
    AWS: {
      DEFAULT_PARAMS: {
        InstanceType: 't1.micro'
      },
      ALLOWED_USER_PARAMS: ['InstanceType'],
      REQUIRED_PARAMS: {
        KeyName: 'moirai'
      },
      TAG_PARAMS: ['Name'],
      ACCESS_KEY: void 0,
      SECRET_KEY: void 0,
      REGION: 'us-east-1',
      APIVERSION: '2014-10-01',
      USERDATA: ''
    },
    LOGGERS: {
      WEB: {
        streams: [
          {
            path: '/var/log/moirai/web-error.log',
            level: "error"
          }, {
            path: '/var/log/moirai/web.log',
            level: "info"
          }
        ]
      },
      WORKER: {
        streams: [
          {
            path: '/var/log/moirai/worker-error.log',
            level: "error"
          }, {
            path: '/var/log/moirai/worker.log',
            level: "info"
          }
        ]
      }
    },
    DEV: false
  };

  deepExtend(config, config_secret);

  module.exports = config;

}).call(this);
