// Generated by CoffeeScript 1.9.1
(function() {
  var _, config, config_secret;

  _ = require('underscore');

  config_secret = require('./config_secret');

  config = {
    COUCHDB: {
      HOST: 'localhost',
      PORT: 5984,
      HTTPS: false,
      SYSTEM_USER: 'admin'
    },
    APP: {
      PORT: 5001
    },
    PRIVATE_KEY_FILE: process.env.HOME + '/.ssh/moirai-dev',
    AUTHORIZED_KEY_DEFAULTS: []
  };

  _.extend(config, config_secret);

  module.exports = config;

}).call(this);
