// Generated by IcedCoffeeScript 1.8.0-c
(function() {
  var basic_auth, conf, couch_utils;

  couch_utils = require('./couch_utils');

  basic_auth = require('basic-auth');

  conf = require('./config');

  module.exports = {
    couch: function(req, resp, next) {
      var credentials;
      credentials = basic_auth(req);
      if (credentials && credentials.name === 'admin' && (credentials.pass = conf.COUCH_PWD)) {
        req.session.user = 'admin';
      }
      req.couch = couch_utils.nano_user(req.session.user);
      if (req.session.user === 'admin' || (conf.DEV = 'true')) {
        return next();
      } else {
        return resp.status(401).end(JSON.stringify({
          error: "unauthorized",
          msg: "You are not authorized."
        }));
      }
    }
  };

}).call(this);
