// Generated by CoffeeScript 1.9.1
(function() {
  var clusters;

  clusters = require('./api/clusters');

  module.exports = function(app) {
    app.get('/moirai/clusters', clusters.handleGetClusters);
    app.post('/moirai/clusters', clusters.handleCreateCluster);
    app.get('/moirai/clusters/:cluster_id', clusters.handleGetCluster);
    app["delete"]('/moirai/clusters/:cluster_id', clusters.handleDestroyCluster);
    app.put('/moirai/clusters/:cluster_id/keys', clusters.handleSetKeys);
    app.put('/moirai/clusters/:cluster_id/start', clusters.handleStartCluster);
    return app.put('/moirai/clusters/:cluster_id/stop', clusters.handleStopCluster);
  };

}).call(this);
