// Generated by CoffeeScript 1.9.3
(function() {
  var clusters, conf, couch_utils, utils;

  clusters = require('./api/clusters');

  couch_utils = require('pantheon-helpers/lib/couch_utils');

  conf = require('./config');

  utils = {};

  utils.shutdownOldInstances = function() {
    var client, instancesToShutdown;
    client = couch_utils.nano_user(conf.COUCHDB.SYSTEM_USER);
    instancesToShutdown = clusters.getInstancesToShutdown(client);
    return clusters.stopInstances(instancesToShutdown);
  };

  utils.shutdownTimer = function() {
    var DAY_IN_MILLIS, firstRun;
    firstRun = new Date();
    firstRun.setDate(firstRun.getDate() + 1);
    firstRun.setHours(3, 0, 0, 0);
    DAY_IN_MILLIS = 24 * 60 * 60 * 1000;
    return setTimeout(firstRun - new Date()).setInterval(shutdownOldInstances, DAY_IN_MILLIS);
  };

  module.exports = utils;

}).call(this);
