// Generated by CoffeeScript 1.9.3
(function() {
  var Promise, _, clusters, conf, scheduler;

  _ = require('underscore');

  Promise = require('pantheon-helpers/lib/promise');

  clusters = require('./api/clusters');

  conf = require('./config');

  scheduler = {};

  scheduler.powerOffOldInstances = function() {
    var instancesToPowerOff;
    instancesToPowerOff = clusters.getOldClusters();
    return clusters.stopInstances(instanceisToPowerOff)["catch"](function(err) {});
  };

  module.exports = scheduler;

}).call(this);
