// Generated by CoffeeScript 1.9.1
(function() {
  var Promise, _, conf, couch_utils, ec2Client, ec2KeyManagement, handlers;

  _ = require('underscore');

  conf = require('./config');

  ec2Client = require('./ec2Client');

  couch_utils = require('./couch_utils');

  ec2KeyManagement = require('./ec2KeyManagement');

  Promise = require('pantheon-helpers/lib/promise');

  handlers = {
    cluster: {
      'c+': function(event, doc) {
        var instance_promises;
        instance_promises = {};
        _.each(event.record.instances, function(event_instance) {
          var instance;
          instance = _.findWhere(doc.instances, {
            id: event_instance.id
          });
          if (instance && (!instance.state || instance.state.indexOf('terminate') < 0) && (instance.aws_id == null)) {
            event_instance.ClientToken = instance.id;
            return instance_promises[event_instance.id] = ec2Client.createInstance(event_instance);
          }
        });
        if (_.isEmpty(instance_promises)) {
          return Promise.resolve();
        }
        return Promise.hashResolveAll(instance_promises).then(function(results) {
          var failed;
          failed = false;
          _.each(results, function(result, instance_id) {
            var instance;
            instance = _.findWhere(doc.instances, {
              id: instance_id
            });
            if (result.state === 'resolved') {
              instance.aws_id = result.value.InstanceId;
              instance.ip = result.value.PrivateIpAddress;
              return delete instance.error;
            } else {
              instance.state = 'create_failed';
              instance.error = result.error;
              return failed = true;
            }
          });
          if (failed) {
            return Promise.reject({
              error: results,
              data: {
                instances: doc.instances
              },
              path: []
            });
          } else {
            return Promise.resolve({
              data: {
                instances: doc.instances
              },
              path: []
            });
          }
        });
      },
      'c-': function(event, doc) {
        var instance_promises;
        if (_.isEmpty(doc.instances)) {
          return Promise.resolve();
        }
        instance_promises = {};
        _.each(doc.instances, function(instance) {
          if (instance.aws_id !== void 0) {
            return instance_promises[instance.id] = ec2Client.destroyInstance(instance.aws_id);
          } else {
            return instance_promises[instance.id] = Promise.resolve();
          }
        });
        return Promise.hashResolveAll(instance_promises).then(function(results) {
          var failed;
          failed = false;
          _.each(results, function(result, instance_id) {
            var instance;
            instance = _.findWhere(doc.instances, {
              id: instance_id
            });
            if (instance.aws_id == null) {
              return null;
            } else if (result.state === 'resolved') {
              return doc.instances.splice(doc.instances.indexOf(instance), 1);
            } else {
              instance.error = result.error;
              instance.state = 'terminate_failed';
              return failed = true;
            }
          });
          if (failed) {
            return Promise.reject({
              error: results,
              data: {
                instances: doc.instances
              },
              path: []
            });
          } else {
            return Promise.resolve({
              data: {
                instances: doc.instances
              },
              path: []
            });
          }
        });
      },
      'k': function(event, doc) {
        var promiseList;
        promiseList = _.map(doc.instances, function(instance) {
          if (instance.aws_id != null) {
            return ec2KeyManagement.setSSHKeys(instance, doc.keys);
          } else {
            return Promise.setTimeout(60 * 1000).then(function() {
              return couch_utils.nano_system_user.use('moirai').get(doc._id, 'promise');
            }).then(function(updatedDoc) {
              var updatedInstance;
              updatedInstance = _.findWhere(updatedDoc.instances, {
                id: instance.id
              });
              if (updatedInstance.aws_id == null) {
                return Promise.reject('Instance has no aws_id defined');
              }
              return ec2KeyManagement.setSSHKeys(updatedInstance, doc.keys);
            });
          }
        });
        return Promise.all(promiseList).then(function() {
          return Promise.resolve();
        })["catch"](function(err) {});
      }
    }
  };

  module.exports = handlers;

}).call(this);
